title: Operating Systems - Sistem Operasi
author: Cicak Bin Kadal
theme: jekyll-theme-midnight

# description: > 
# Laman ini berisi tautan-tautan seputar mata kuliah Sistem Operasi seperti bahan kuliah, soal ujian, dan bahan laboratorium. Situs ini dikelola oleh VauLSMorg (vlsm.org) sejak semester ganjil 2016/2017 lalu. 

