title: Operating Systems - Sistem Operasi
description: (V025-20190712) Laman ini berisi tautan-tautan seputar mata kuliah Sistem Operasi seperti bahan kuliah, soal ujian, dan bahan laboratorium. Situs ini dikelola oleh VauLSMorg (vlsm.org) sejak semester ganjil 2016/2017 lalu. 
author: Mr. Yoda Yoda
theme: jekyll-theme-midnight

show_downloads: false
google_analytics:

theme: jekyll-theme-hacker
# theme: jekyll-theme-merlot
# theme: jekyll-theme-midnight

# github:
#    zip_url: https://github.com/UI-FASILKOM-OS/SistemOperasi/archive/master.zip
#    tar_url: https://github.com/UI-FASILKOM-OS/SistemOperasi/archive/master.tar.gz

github: [metadata]

